"$schema" = 'https://starship.rs/config-schema.json'
scan_timeout = 10
command_timeout = 1500
add_newline = false

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$hg_branch\
$line_break\
$character"""

right_format = """
$c\
$cmake\
$dotnet\
$haskell\
$lua\
$python\
$rust\
$zig\
$jobs\
$cmd_duration\
$time\
"""

[directory]
fish_style_pwd_dir_length = 2
truncation_length = 8
truncation_symbol = "…/"

[character]
success_symbol = "[❯](bold fg:#ff57c9)"
error_symbol = '[✗](bold red) '

[time]
disabled = false

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[git_metrics]
disabled = false
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[c]
symbol = 'C/C++ '
detect_files = ["CMakeLists.txt"]
detect_extensions = ['cpp', 'hpp']
