theme = "onedark"

[editor]
line-number = "relative"
mouse = true
true-color = true
scrolloff = 8
scroll-lines = 1
color-modes = true
auto-save = true
bufferline = "multiple"
auto-pairs = true
shell = ["zsh", "-c"]
completion-trigger-len = 1
idle-timeout = 80

[editor.search]
smart-case = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "╎", "┆", "┊", "⸽"

[editor.statusline]
left = [
  "mode",
  "spacer",
  "version-control",
  "file-name",
  "file-type",
  "diagnostics",
]
center = []
right = [
  "spinner",
  "file-encoding",
  "selections",
  "primary-selection-length",
  "position",
  "position-percentage",
]
separator = "│"
